name: gtfs4ev
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=23.2.0
  - azure-core-cpp=1.10.3
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blas=1.0
  - blosc=1.21.5
  - bottleneck=1.3.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - certifi=2023.11.17
  - cfitsio=4.3.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.12.1
  - expat=2.5.0
  - fiona=1.9.5
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.8.2
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgdal=3.8.2
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.3
  - libzip=1.10.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - minizip=4.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - networkx=3.2.1
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.1.4
  - pcre2=10.42
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.42.2
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.1
  - pthread-stubs=0.4
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.1
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - re2=2023.06.02
  - requests=2.31.0
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - shapely=2.0.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=3.2.0
  - tiledb=2.19.0
  - tk=8.6.13
  - tzdata=2023d
  - ucrt=10.0.22621.0
  - uriparser=0.9.7
  - urllib3=2.1.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
